In [1]:
                      ### ESERCITAZIONE FINALE 
                ### IL CASO DI TOYSGROUP IN PYTHON

In [2]:
### TASK 1 PYTHON DI BASE SUI DATI FORNITI ###

In [3]:
## Task 1 - Punto 1: lettura dei dati
## Leggo products.csv e sales.json come liste di dizionari,
## costruisco il dizionario regions {RegionID: (State, SalesRegion)} 
## e il set delle categorie.

In [4]:
import pandas as pd
## Leggo i file e li trasformo in liste di dizzionari
products = pd.read_csv("products.csv").to_dict(orient="records")
vendite = pd.read_json("sales.json").to_dict(orient="records")

## Costruisco il dizzionario delle regioni
regions_df = pd.read_excel("regions.xlsx")
regions = {}
for riga in regions_df.to_dict(orient="records"):
    regions[riga["RegionID"]] = (riga["State"], riga["SalesRegion"])

## Costruisco il set delle categorie
categorie = set()
for p in products:
    categorie.add(p["Category"])

## Stampo i risultati

print(len(products))
print(len(vendite))
print(products)
print(regions)
print(categorie)

12
2000
[{'ProductID': 1, 'ProductName': 'Bici Junior', 'Category': 'Outdoor', 'ListPrice': 129.0}, {'ProductID': 2, 'ProductName': 'Bici BMX', 'Category': 'Outdoor', 'ListPrice': 189.0}, {'ProductID': 3, 'ProductName': 'Monopattino', 'Category': 'Outdoor', 'ListPrice': 79.0}, {'ProductID': 4, 'ProductName': 'Pallone Calcio', 'Category': 'Outdoor', 'ListPrice': 19.9}, {'ProductID': 5, 'ProductName': 'Racchette Beach', 'Category': 'Outdoor', 'ListPrice': 14.5}, {'ProductID': 6, 'ProductName': 'Puzzle 1000', 'Category': 'Giochi da tavolo', 'ListPrice': 17.9}, {'ProductID': 7, 'ProductName': "Gioco dell'Oca", 'Category': 'Giochi da tavolo', 'ListPrice': 12.5}, {'ProductID': 8, 'ProductName': 'Scacchi Legno', 'Category': 'Giochi da tavolo', 'ListPrice': 34.0}, {'ProductID': 9, 'ProductName': 'Costruzioni 500', 'Category': 'Giocattoli', 'ListPrice': 39.9}, {'ProductID': 10, 'ProductName': 'Bambola Classica', 'Category': 'Giocattoli', 'ListPrice': 24.9}, {'ProductID': 11, 'ProductName': 'Robot RC', 'Category': 'Giocattoli', 'ListPrice': 89.0}, {'ProductID': 12, 'ProductName': 'Macchinina RC', 'Category': 'Giocattoli', 'ListPrice': 59.0}]
{1: ('Italia', 'Sud Europa'), 2: ('Francia', 'Sud Europa'), 3: ('Spagna', 'Sud Europa'), 4: ('Germania', 'Centro Europa'), 5: ('Austria', 'Centro Europa'), 6: ('Svizzera', 'Centro Europa'), 7: ('Svezia', 'Nord Europa'), 8: ('Norvegia', 'Nord Europa'), 9: ('Danimarca', 'Nord Europa')}
{'Giocattoli', 'Outdoor', 'Giochi da tavolo'}

In [5]:
## Task 1-Punto 2: Fascia di prezzo
## con una list comprehension e un costrutto if/elif/else assegno a ogni
## prodotto la fascia di prezzo: Bassa sotto 20 €, Media fino a 60 €, Alta oltre.

In [6]:
def fascia_prezzo(prezzo):
    if prezzo < 20:
        return "Bassa"
    elif prezzo <= 60:
        return "Media"
    else:
        return "Alta"


prodotti_con_fascia = [
    {"ProductName":p["ProductName"],"ListPrice": p["ListPrice"], "Fascia": fascia_prezzo(p["ListPrice"])}
    for p in products
]

for p in prodotti_con_fascia:
    print(p)

{'ProductName': 'Bici Junior', 'ListPrice': 129.0, 'Fascia': 'Alta'}
{'ProductName': 'Bici BMX', 'ListPrice': 189.0, 'Fascia': 'Alta'}
{'ProductName': 'Monopattino', 'ListPrice': 79.0, 'Fascia': 'Alta'}
{'ProductName': 'Pallone Calcio', 'ListPrice': 19.9, 'Fascia': 'Bassa'}
{'ProductName': 'Racchette Beach', 'ListPrice': 14.5, 'Fascia': 'Bassa'}
{'ProductName': 'Puzzle 1000', 'ListPrice': 17.9, 'Fascia': 'Bassa'}
{'ProductName': "Gioco dell'Oca", 'ListPrice': 12.5, 'Fascia': 'Bassa'}
{'ProductName': 'Scacchi Legno', 'ListPrice': 34.0, 'Fascia': 'Media'}
{'ProductName': 'Costruzioni 500', 'ListPrice': 39.9, 'Fascia': 'Media'}
{'ProductName': 'Bambola Classica', 'ListPrice': 24.9, 'Fascia': 'Media'}
{'ProductName': 'Robot RC', 'ListPrice': 89.0, 'Fascia': 'Alta'}
{'ProductName': 'Macchinina RC', 'ListPrice': 59.0, 'Fascia': 'Media'}

In [7]:
## Task 1 - Punto 3:  Scrivo la funzione fatturato_categoria(vendite, prodotti, categoria)
## che con un ciclo for somma SalesAmount della categoria, salta i valori mancanti (Nan) e restituisce 
## il totale con return.

In [8]:
import math

def fatturato_categoria(vendite, prodotti, categoria):
    # rubrica di appoggio: ProductID -> Category
    categoria_di = {}
    for p in prodotti:
        categoria_di[p["ProductID"]] = p["Category"]

    totale = 0
    for v in vendite:
        importo = v["SalesAmount"]
        if math.isnan(importo):
            continue
        if categoria_di[v["ProductID"]] == categoria:
            totale += importo
    return totale

for c in categorie:
    print(c, round(fatturato_categoria(vendite, products, c), 2))

Giocattoli 174832.0
Outdoor 331998.4
Giochi da tavolo 53245.1

In [9]:
## Task 1 -Punto 4 Con un ciclo while conto le transazioni necessarie a superare 10.000 € 
## di fatturato cumulato; mostro le prime cinque transazioni con vendite[:5].

In [10]:
import math
soglia = 10000
cumulato = 0
contate = 0
i = 0

while cumulato <= soglia and i < len(vendite):
    importo = vendite [i]["SalesAmount"]
    if not math.isnan(importo):
        cumulato += importo
        contate += 1
    i += 1
print("Transazioni necessarie:",contate)
print("Righe scorse (comprese quelle senza importo):",i)
print("Fatturato cumulato:",round(cumulato,2))

for v in vendite [:5]:
    print(v)

Transazioni necessarie: 52
Righe scorse (comprese quelle senza importo): 56
Fatturato cumulato: 10164.8
{'SalesID': 1194, 'ProductID': 6, 'RegionID': 7, 'ResellerID': 283, 'SalesDate': '2023-01-01', 'Quantity': 4.0, 'SalesAmount': 71.6}
{'SalesID': 859, 'ProductID': 6, 'RegionID': 8, 'ResellerID': 28, 'SalesDate': '2023-01-02', 'Quantity': 7.0, 'SalesAmount': nan}
{'SalesID': 1747, 'ProductID': 12, 'RegionID': 3, 'ResellerID': 281, 'SalesDate': '2023-01-02', 'Quantity': 2.0, 'SalesAmount': 118.0}
{'SalesID': 279, 'ProductID': 3, 'RegionID': 7, 'ResellerID': 128, 'SalesDate': '2023-01-02', 'Quantity': 3.0, 'SalesAmount': nan}
{'SalesID': 1470, 'ProductID': 1, 'RegionID': 6, 'ResellerID': 137, 'SalesDate': '2023-01-04', 'Quantity': 4.0, 'SalesAmount': nan}

In [11]:
### DEFINIZIONI ###
## LISTA e' una sequenza ordinata e mutabile di elementi, accessibile per indice.
## puo contenere dupplicati e si scrive con []
## TUPLA e' una sequenza ordinata e immutabile di elementi, accessibile per indice.
## puo contenere dupplicati e si scrive con ()
## SET e' una collezione non ordinata di elementi unici, non eccessibile per indice.
## non contiene dupplicati e si scrive {}
## DIZIONARIO e' una collezione di coppie chiave --> valore, accessibile per chiave.
## le chiavi devono essere uniche e immutabili, i valori possono essere dupplicati. Si scrive{}

In [12]:
### TASK 2 · LETTURA E ISPEZIONE DEI DATI ###

In [13]:
## Task 2 - Punto 1: lettura e ispezione dei dati
## Leggo i quattro file in DataFrame e riporto per ciascuno dimensioni, struttura, prime e ultime righe.

In [14]:
import pandas as pd

df_products = pd.read_csv("products.csv")
df_regions = pd.read_excel("regions.xlsx")
df_sales = pd.read_json("sales.json")
df_resellers = pd.read_csv("resellers.csv")

tabelle = {
    "products": df_products,
    "regions": df_regions,
    "sales": df_sales,
    "resellers": df_resellers,
}
for nome, df in tabelle.items():
    print("=====", nome, "=====")
    print("Righe e colonne:", df.shape)
    df.info()
    display(df.head())
    display(df.tail())

===== products =====
Righe e colonne: (12, 4)
<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ProductID    12 non-null     int64
 1   ProductName  12 non-null     str
 2   Category     12 non-null     str
 3   ListPrice    12 non-null     float64
dtypes: float64(1), int64(1), str(2)
memory usage: 788.0 bytes

   ProductID      ProductName Category  ListPrice
0          1      Bici Junior  Outdoor      129.0
1          2         Bici BMX  Outdoor      189.0
2          3      Monopattino  Outdoor       79.0
3          4   Pallone Calcio  Outdoor       19.9
4          5  Racchette Beach  Outdoor       14.5

    ProductID       ProductName          Category  ListPrice
7           8     Scacchi Legno  Giochi da tavolo       34.0
8           9   Costruzioni 500        Giocattoli       39.9
9          10  Bambola Classica        Giocattoli       24.9
10         11          Robot RC        Giocattoli       89.0
11         12     Macchinina RC        Giocattoli       59.0

===== regions =====
Righe e colonne: (9, 3)
<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   RegionID     9 non-null      int64
 1   State        9 non-null      str
 2   SalesRegion  9 non-null      str
dtypes: int64(1), str(2)
memory usage: 515.0 bytes

   RegionID     State    SalesRegion
0         1    Italia     Sud Europa
1         2   Francia     Sud Europa
2         3    Spagna     Sud Europa
3         4  Germania  Centro Europa
4         5   Austria  Centro Europa

   RegionID      State    SalesRegion
4         5    Austria  Centro Europa
5         6   Svizzera  Centro Europa
6         7     Svezia    Nord Europa
7         8   Norvegia    Nord Europa
8         9  Danimarca    Nord Europa

===== sales =====
Righe e colonne: (2000, 7)
<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   SalesID      2000 non-null   int64
 1   ProductID    2000 non-null   int64
 2   RegionID     2000 non-null   int64
 3   ResellerID   2000 non-null   int64
 4   SalesDate    2000 non-null   str
 5   Quantity     1900 non-null   float64
 6   SalesAmount  1900 non-null   float64
dtypes: float64(2), int64(4), str(1)
memory usage: 129.0 KB

   SalesID  ProductID  RegionID  ResellerID   SalesDate  Quantity  SalesAmount
0     1194          6         7         283  2023-01-01       4.0         71.6
1      859          6         8          28  2023-01-02       7.0          NaN
2     1747         12         3         281  2023-01-02       2.0        118.0
3      279          3         7         128  2023-01-02       3.0          NaN
4     1470          1         6         137  2023-01-04       4.0          NaN

,SalesID,ProductID,RegionID,ResellerID,SalesDate,Quantity,SalesAmount
1995,326,3,1,280,2025-12-27,4.0,316.0
1996,394,7,2,256,2025-12-29,5.0,62.5
1997,196,4,8,50,2025-12-29,5.0,99.5
1998,878,4,4,27,2025-12-30,8.0,159.2
1999,1278,9,5,57,2025-12-30,9.0,359.1

===== resellers =====
Righe e colonne: (300, 7)
<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ResellerID          300 non-null    int64
 1   RegionID            300 non-null    int64
 2   Ordini12m           300 non-null    int64
 3   GiorniUltimoOrdine  300 non-null    int64
 4   ScontoMedio         300 non-null    float64
 5   Reclami             300 non-null    int64
 6   Churn               300 non-null    int64
dtypes: float64(1), int64(6)
memory usage: 16.5 KB

,ResellerID,RegionID,Ordini12m,GiorniUltimoOrdine,ScontoMedio,Reclami,Churn
0,1,1,14,65,0.131,1,0
1,2,7,9,149,0.117,1,0
2,3,6,21,1,0.065,2,0
3,4,4,18,162,0.011,1,1
4,5,4,22,98,0.120,0,0

,ResellerID,RegionID,Ordini12m,GiorniUltimoOrdine,ScontoMedio,Reclami,Churn
295,296,5,18,145,0.218,1,0
296,297,8,17,104,0.048,0,0
297,298,4,16,141,0.055,2,0
298,299,3,13,113,0.164,0,0
299,300,1,12,116,0.072,0,0

In [15]:
## Task 2 - Punto 2 con .describe() individuo minimo, massimo e media di Quantity e SalesAmount; 
## converto le due colonne in array NumPy e calcolo con un'operazione vettoriale il prezzo unitario di ogni vendita.
## Quantity = min 1, max 14, mean 4,97
## SalesAmount = min 12.5, 2457, 294.78
### i prezzi unitari calcolati (12,5, 14,5, 17,9, 19,9, ...) coincidono con i prezzi di listino dei prodotti,
### quindi i dati sono consistenti.

In [16]:
import numpy as np
#statistiche descrittive delle due colonne
display(df_sales[["Quantity","SalesAmount"]].describe())

#conversione in array NumPy
quantita = df_sales["Quantity"].to_numpy()
importi = df_sales["SalesAmount"].to_numpy()

#operazione vettoriale : prezzo unitario di ogni vendita
prezzo_unitario = importi / quantita

print(prezzo_unitario[:10])
print("Valori mancanti nel risultato:", np.isnan(prezzo_unitario).sum())

          Quantity  SalesAmount
count  1900.000000  1900.000000
mean      4.966316   294.776579
std       2.206535   305.261212
min       1.000000    12.500000
25%       3.000000    89.000000
50%       5.000000   177.000000
75%       6.000000   387.000000
max      14.000000  2457.000000

[17.9  nan 59.   nan  nan 12.5 79.  79.  12.5  nan]
Valori mancanti nel risultato: 198

In [17]:
## Task 2 - Punto 3: selezionare con .loc[] e una maschera booleana i prodotti di una categoria con 
## ListPrice superiore a 30 €; con .iloc[] le righe da 10 a 19 e le prime tre colonne di sales.

In [18]:
# .loc[] con maschera booleana: prodotti Outdoor con prezzo > 30 €
maschera = (df_products["Category"] == "Outdoor") & (df_products["ListPrice"] > 30)
prodotti_selezionati = df_products.loc[maschera, ["ProductName", "Category", "ListPrice"]]
display(prodotti_selezionati)

# .iloc[]: righe da 10 a 19 e prime tre colonne di sales
selezione_sales = df_sales.iloc[10:20, :3]
display(selezione_sales)
print("Dimensioni della selezione:", selezione_sales.shape)

   ProductName Category  ListPrice
0  Bici Junior  Outdoor      129.0
1     Bici BMX  Outdoor      189.0
2  Monopattino  Outdoor       79.0

    SalesID  ProductID  RegionID
10      218          1         8
11     1136          1         9
12     1326          3         4
13     1063          9         7
14     1606         10         8
15     1283         12         1
16       98          3         4
17      156          6         8
18     1642         12         5
19     1644          4         7

Dimensioni della selezione: (10, 3)

In [19]:
### Definizione: Series e DataFrame , .loc[] e .iloc[]

## Una Series è una singola colonna di dati con il suo indice (per esempio df["ListPrice"]). 
## Un DataFrame è una tabella formata da più colonne che condividono lo stesso indice (per esempio df_products): si può vedere come un insieme di Series affiancate.

## .loc[] seleziona righe e colonne per etichetta (nome della colonna o valore dell'indice) o con una maschera booleana, e l'estremo finale di un intervallo è incluso.
## .iloc[] seleziona per posizione intera, contando da 0, e l'estremo finale è escluso.

In [20]:
### TASK 3A Dati mancanti, filtri e ordinamento ###

In [21]:
## Task 3a - Punto 1: valori mancanti nelle vendite
## Creo una copia del DataFrame delle vendite (df_sales_clean) e conto i valori mancanti per colonna, 
##calcolandone anche la percentuale sul totale delle righe.

In [22]:
df_sales_clean = df_sales.copy()

nan_prima = pd.DataFrame({
    "NaN": df_sales_clean.isna().sum(),
    "Percentuale (%)": (df_sales_clean.isna().sum() / len(df_sales_clean) * 100).round(2),
})
display(nan_prima)

             NaN  Percentuale (%)
SalesID        0              0.0
ProductID      0              0.0
RegionID       0              0.0
ResellerID     0              0.0
SalesDate      0              0.0
Quantity     100              5.0
SalesAmount  100              5.0

In [23]:
## Task 3a - Punto 2: imputazione e rimozione dei valori mancanti
## Imputo Quantity con la mediana della colonna, calcolata sui valori presenti prima del fillna(). 
## Elimino con dropna() le righe con SalesAmount mancante, perché l'importo è il dato da analizzare e inventarlo falserebbe il fatturato.

## Righe rimosse: 100 (da 2000 a 1900).

In [24]:
righe_prima = len(df_sales_clean)

# 1) Imputazione di Quantity con la mediana (calcolata sui valori presenti)
mediana_quantity = df_sales_clean["Quantity"].median()
df_sales_clean["Quantity"] = df_sales_clean["Quantity"].fillna(mediana_quantity)

# 2) Eliminazione delle righe con SalesAmount mancante
df_sales_clean = df_sales_clean.dropna(subset=["SalesAmount"])

righe_rimosse = righe_prima - len(df_sales_clean)
print("Mediana di Quantity:", mediana_quantity)
print("Righe rimosse:", righe_rimosse)
print("Righe rimaste:", len(df_sales_clean))

# Tabella dei NaN prima e dopo il trattamento
nan_dopo = df_sales_clean.isna().sum()
confronto = pd.DataFrame({"NaN prima": nan_prima["NaN"], "NaN dopo": nan_dopo})
display(confronto)

Mediana di Quantity: 5.0
Righe rimosse: 100
Righe rimaste: 1900

             NaN prima  NaN dopo
SalesID              0         0
ProductID            0         0
RegionID             0         0
ResellerID           0         0
SalesDate            0         0
Quantity           100         0
SalesAmount        100         0

In [25]:
## Task 3a - Punto 3: transazioni sopra il 90° percentile
## Con quantile(0.9) calcolo la soglia del 90° percentile di SalesAmount e con query() estraggo le transazioni
## con importo superiore. Le ordino per data crescente e, a parità di data, per importo decrescente. Verifica con head(10).

## Soglia del 90° percentile: 756,00 €. Transazioni sopra la soglia: 162.

In [26]:
soglia_90 = df_sales_clean["SalesAmount"].quantile(0.9)

top_vendite = df_sales_clean.query("SalesAmount > @soglia_90")
top_vendite = top_vendite.sort_values(by=["SalesDate", "SalesAmount"], ascending=[True, False])

print("Soglia 90° percentile:", soglia_90)
print("Transazioni sopra la soglia:", len(top_vendite))
display(top_vendite.head(10))

Soglia 90° percentile: 756.0
Transazioni sopra la soglia: 162

,SalesID,ProductID,RegionID,ResellerID,SalesDate,Quantity,SalesAmount
32,1045,2,4,82,2023-01-16,6.0,1134.0
49,1872,2,7,204,2023-01-25,5.0,945.0
52,1639,1,3,299,2023-01-27,9.0,1161.0
102,296,2,9,202,2023-02-25,5.0,945.0
118,1462,2,2,224,2023-03-03,5.0,945.0
121,1221,1,8,149,2023-03-05,8.0,1032.0
123,1753,2,8,151,2023-03-05,5.0,945.0
168,283,2,2,100,2023-03-30,11.0,2079.0
217,1679,1,4,22,2023-04-27,5.0,774.0
221,832,2,4,82,2023-04-28,6.0,1134.0

In [27]:
### Definizione: imputazione dei dati mancanti

##Cos’è l’imputazione
## Imputare significa sostituire un valore mancante con un valore stimato, per non perdere tutta la riga. 
##La media è semplice ma risente dei valori estremi. La mediana è più robusta, ed è per questo che l’ho usata. 
##L’eliminazione della riga conviene quando i mancanti sono pochi o riguardano il dato da analizzare, ma riduce il numero di osservazioni.

##- **Media:** semplice, adatta a distribuzioni simmetriche e senza valori estremi, ma molto influenzata dagli outlier.
##- **Mediana:** il valore centrale dei dati ordinati, robusta agli outlier e preferibile quando la distribuzione è asimmetrica (è la scelta fatta per Quantity).
##- **Eliminazione della riga:** adatta quando i mancanti sono pochi o riguardano la variabile da analizzare, perché non inventa dati (è la scelta fatta per SalesAmount), 
## ma riduce il campione e può introdurre distorsioni se i dati non mancano a caso.

## **Effetto sulla distribuzione:** imputare con un unico valore concentra molte osservazioni su quel punto, quindi la distribuzione diventa più "appuntita" e la variabilità diminuisce.
## Eliminare le righe mantiene la forma dei dati, ma riduce il numero di osservazioni.

In [28]:
### TASK 3B · AGGREGAZIONI E COMBINAZIONI DEI DATAFRAME

In [29]:
## Task 3b - Punto 1: unione di sales con products e regions
## Unisco le vendite pulite (df_sales_clean) con products su ProductID e con regions su RegionID, con how="left" per non perdere nessuna vendita. 
## Verifico che il numero di righe resti quello di sales e che non ci siano valori mancanti introdotti dal merge.

In [30]:
df_full=pd.merge(df_sales_clean, df_products, on="ProductID", how="left")
df_full=pd.merge(df_full, df_regions, on="RegionID", how="left")

print("Righe di sales:", len(df_sales_clean))
print("Righe dopo il merge:",len(df_full))
print("Colonne dopo il merge:",list(df_full.columns))

print("Valori mancanti indtrodotti dal merge:")
print(df_full[["ProductName","Category","ListPrice","State","SalesRegion"]].isna().sum())

display(df_full.head())

Righe di sales: 1900
Righe dopo il merge: 1900
Colonne dopo il merge: ['SalesID', 'ProductID', 'RegionID', 'ResellerID', 'SalesDate', 'Quantity', 'SalesAmount', 'ProductName', 'Category', 'ListPrice', 'State', 'SalesRegion']
Valori mancanti indtrodotti dal merge:
ProductName    0
Category       0
ListPrice      0
State          0
SalesRegion    0
dtype: int64

,SalesID,ProductID,RegionID,ResellerID,SalesDate,Quantity,SalesAmount,ProductName,Category,ListPrice,State,SalesRegion
0,1194,6,7,283,2023-01-01,4.0,71.6,Puzzle 1000,Giochi da tavolo,17.9,Svezia,Nord Europa
1,1747,12,3,281,2023-01-02,2.0,118.0,Macchinina RC,Giocattoli,59.0,Spagna,Sud Europa
2,947,7,8,166,2023-01-04,6.0,75.0,Gioco dell'Oca,Giochi da tavolo,12.5,Norvegia,Nord Europa
3,577,3,4,285,2023-01-04,3.0,237.0,Monopattino,Outdoor,79.0,Germania,Centro Europa
4,78,3,8,107,2023-01-04,3.0,237.0,Monopattino,Outdoor,79.0,Norvegia,Nord Europa

In [31]:
## Task 3b - Punto 2: fatturato, quantità e transazioni per categoria e per area
## Con groupby() e agg() calcolo, per Category e per SalesRegion, fatturato totale, quantità totale e numero di transazioni, 
## ordinando per fatturato decrescente.

## La categoria con il fatturato più alto è OUTDOOR (331.998,40 €).

In [32]:
per_categoria=(
    df_full.groupby("Category")
    .agg(Fatturato=("SalesAmount","sum"),
         Quantita=("Quantity","sum"),
         Transazioni=("SalesID","count"))
    .sort_values("Fatturato", ascending=False)
)
per_regione = (
    df_full.groupby("SalesRegion")
    .agg(Fatturato=("SalesAmount", "sum"),
         Quantita=("Quantity", "sum"),
         Transazioni=("SalesID", "count"))
    .sort_values("Fatturato", ascending=False)
)

display(per_categoria)
display(per_regione)

                  Fatturato  Quantita  Transazioni
Category
Outdoor            331998.4    3800.0          767
Giocattoli         174832.0    3225.0          644
Giochi da tavolo    53245.1    2416.0          489

               Fatturato  Quantita  Transazioni
SalesRegion
Centro Europa   201062.2    3413.0          698
Nord Europa     190189.0    3175.0          633
Sud Europa      168824.3    2853.0          569

In [ ]:
## Task 3b - Punto 3: separazione e ricomposizione delle vendite 2025
## Separo le vendite del 2025 dalle altre con un filtro sulla data e le ricompongo con pd.concat(),
## verificando che il numero di righe coincida con l'originale.

In [34]:
vendite_2025=df_full[df_full["SalesDate"]>="2025-01-01"]
altre_vendite=df_full[df_full["SalesDate"]<"2025-01-01"]

df_ricomposto=pd.concat([altre_vendite,vendite_2025])
print("Vendite 2025:",len(vendite_2025))
print("Altre vendite:",len(altre_vendite))
print("Somma delle due parti:",len(vendite_2025)+len(altre_vendite))
print("Righe originali:",len(df_full))
print("Righe ricomposte:",len(df_ricomposto))

Vendite 2025: 640
Altre vendite: 1260
Somma delle due parti: 1900
Righe originali: 1900
Righe ricomposte: 1900

In [ ]:
### Definizione: merge(), join() e concat()

## MERGE() unisce due tabelle affiancando le colonne, in base a una o più colonne chiave in comune (come fatto con ProductID e RegionID).
## JOIN() unisce due tabelle in base al loro indice, invece che a colonne chiave.
## CONCAT() accoda tabelle una sotto l'altra (righe) o una accanto all'altra (colonne), senza cercare corrispondenze.

In [ ]:
### TASK 3C SERIE TEMPORALI DI VENDITA

In [ ]:
## Task 3c - Punto 1: conversione di SalesDate in formato data
## Converto SalesDate da testo a datetime con pd.to_datetime() e verifico il nuovo tipo con .dtypes.

In [35]:
df_full["SalesDate"]=pd.to_datetime(df_full["SalesDate"])

print(df_full.dtypes)

SalesID                 int64
ProductID               int64
RegionID                int64
ResellerID              int64
SalesDate      datetime64[us]
Quantity              float64
SalesAmount           float64
ProductName               str
Category                  str
ListPrice             float64
State                     str
SalesRegion               str
dtype: object

In [ ]:
## Task 3c - Punto 2: anno, mese e giorno della settimana
## Con l'accessor .dt estraggo da SalesDate anno, mese e giorno della settimana (0 = lunedì, 6 = domenica) in tre nuove colonne.

In [36]:
df_full["Anno"] = df_full["SalesDate"].dt.year
df_full["Mese"] = df_full["SalesDate"].dt.month
df_full["GiornoSettimana"] = df_full["SalesDate"].dt.dayofweek

display(df_full[["SalesDate", "Anno", "Mese", "GiornoSettimana"]].head())

   SalesDate  Anno  Mese  GiornoSettimana
0 2023-01-01  2023     1                6
1 2023-01-02  2023     1                0
2 2023-01-04  2023     1                2
3 2023-01-04  2023     1                2
4 2023-01-04  2023     1                2

In [ ]:
## Task 3c - Punto 3: fatturato mensile e variazione percentuale
## Calcolo con groupby() su anno e mese il fatturato mensile e, con pct_change(), la variazione percentuale rispetto al mese precedente.

## Il mese di picco del fatturato è maggio 2025 (29.368,30 €).

In [37]:
fatturato_mensile = (
    df_full.groupby(["Anno", "Mese"], as_index=False)["SalesAmount"].sum()
    .rename(columns={"SalesAmount": "Fatturato"})
)
fatturato_mensile["Variazione %"] = (fatturato_mensile["Fatturato"].pct_change() * 100).round(2)

print("Mesi nella serie:", len(fatturato_mensile))
display(fatturato_mensile)

mese_max = fatturato_mensile.loc[fatturato_mensile["Fatturato"].idxmax()]
print("Mese con il fatturato massimo:", int(mese_max["Mese"]), "/", int(mese_max["Anno"]), "con", mese_max["Fatturato"], "€")

Mesi nella serie: 36

    Anno  Mese  Fatturato  Variazione %
0   2023     1    11499.8           NaN
1   2023     2     9414.9        -18.13
2   2023     3    14917.2         58.44
3   2023     4    11077.9        -25.74
4   2023     5    10806.7         -2.45
5   2023     6    11637.3          7.69
6   2023     7    10161.0        -12.69
7   2023     8    15387.5         51.44
8   2023     9    14361.2         -6.67
9   2023    10    13340.5         -7.11
10  2023    11    11597.0        -13.07
11  2023    12    11604.4          0.06
12  2024     1    17359.8         49.60
13  2024     2     9701.8        -44.11
14  2024     3    20455.7        110.84
15  2024     4    16703.8        -18.34
16  2024     5    13579.1        -18.71
17  2024     6    18679.5         37.56
18  2024     7    16802.9        -10.05
19  2024     8    17218.8          2.48
20  2024     9    12921.5        -24.96
21  2024    10    15710.2         21.58
22  2024    11    16276.4          3.60
23  2024    12    11765.5        -27.71
24  2025     1    14385.1         22.27
25  2025     2    23337.1         62.23
26  2025     3    16348.2        -29.95
27  2025     4    21363.6         30.68
28  2025     5    29368.3         37.47
29  2025     6    17765.2        -39.51
30  2025     7    14791.0        -16.74
31  2025     8    18042.4         21.98
32  2025     9    21273.2         17.91
33  2025    10    20215.7         -4.97
34  2025    11    16428.7        -18.73
35  2025    12    13776.6        -16.14

Mese con il fatturato massimo: 5 / 2025 con 29368.3 €

In [ ]:
## Task 3c - Punto 4: colonna Recente
## Trovo l'ultima data del dataset e calcolo, con operazioni tra date e .dt.days, quanti giorni separano ogni vendita da essa. Recente è True se la vendita è avvenuta entro 180 giorni dall'ultima data, False altrimenti.

## Vendite con Recente = True: 315.

In [38]:
ultima_data = df_full["SalesDate"].max()
df_full["Recente"] = (ultima_data - df_full["SalesDate"]).dt.days <= 180

print("Ultima data nel dataset:", ultima_data)
print("Vendite recenti (Recente = True):", df_full["Recente"].sum())
display(df_full["Recente"].value_counts())

Ultima data nel dataset: 2025-12-30 00:00:00
Vendite recenti (Recente = True): 315

Recente
False    1585
True      315
Name: count, dtype: int64